---
framework: mocha
blacklist: 
  - "test/unit/adapters/http.js##supports http with nodejs##should allow passing JSON"
coverageThreshold: 
  branches: 80
  functions: 80
  lines: 80
  statements: 80
postMerge: 
  pattern: 
    - test/unit/**/*.js
preMerge: 
  pattern: 
    - test/unit/**/*.js
postRun: 
  - "node --version"
preRun: 
  - "npm i"
