---
framework: mocha
blocklist: 
  - "test/unit/adapters/http3.js##supports http with nodejs##should allow passing JSON"
coverageThreshold: 
  branches: 80
  functions: 80
  lines: 80
  statements: 80
postMerge: 
  pattern: 
    - test/unit/**/*.js
preMerge: 
  pattern: 
    - test/unit/**/*.js
postRun:
  command: 
    - "node --version"
preRun:
  command:
    - "npm i"
