---
framework: mocha
blocklist: 
  - "test/unit/adapters/http3.js##supports http with nodejs##should allow passing JSON with BOM"
  - "test/unit/adapters/http3.js##supports http with nodejs##should allow passing JSON"
preRun:
  command:
    - "npm i"
postMerge: 
  pattern: 
    - test/unit/**/*.js
preMerge: 
  pattern: 
    - test/unit/**/*.js
postRun:
  command: 
    - "node --version"
