--- 
blacklist: 
  - "test/unit/adapters/http.js##supports http with nodejs##should redirect"
  - "test/unit/adapters/http.js##supports http with nodejs##should allow passing JSON"
  - "test/unit/adapters/http.js##supports http with nodejs##should support sockets"
coverageThreshold: 
  branches: 80
  functions: 80
  lines: 80
  statements: 80
framework: mocha
postmerge: 
  pattern: 
    - test/unit/adapters/**/*.js
postrun: 
  - "node --version"
premerge: 
  - test/unit/adapters/**/*.js
prerun: 
  - "npm i"
stability: 
  consecutive_runs: 5
version: 2.0
