--- 
blacklist: 
  - "test/unit/adapters/http.js##supports http with nodejs##should allow passing JSON"
coverageThreshold: 
  branches: 80
  functions: 80
  lines: 80
  statements: 80
framework: mocha
postmerge: 
  pattern: 
    - test/unit/**/*.js
postrun: 
  - "node --version"
premerge: 
  - test/unit/**/*.js
prerun: 
  - "npm i"
version: 2.0
